# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d9494f0019a246b2f3f437ddce40bacb6b86ef733cd6feb43605dca501bcb21ec0697158a31fafecf7578d2fb2e326255bdf435aba4e2c49721687196bfbd41

test:
  secret_key_base: 38d952eff082d4bbb3f8a44bff4e26d986ee345b088d5fa8a482a3fe699235db785a2501586f0d265b77b16e98219278d7f6719a4ff13e708bd9104632a5f5ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
