# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e300c7c07908d17293b997f0583a0bf619f0112644f194f1699c4d48c453ce774d1a293ca0974101f233e3333a0892585ab64152eee619773f8c51edfa0cad2d

test:
  secret_key_base: f237fc074e4b2886892f68f4e4667dc74ef65a8d6209c9f4a31232aaf83037d8ae50f3ee9e9274affdedceb9a46a2eb74b08d1a79ebdd28c68e1508a34f1643c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
